config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  Spree::Core::Engine.add_routes do
    namespace :api, defaults: { format: 'json' } do
      namespace :v1 do
        resources :addresses, except: [:new, :edit], controller: :user_addresses do
          collection do
            patch 'default', to: 'user_addresses#default_resources'
          end
        end

        resource :contact, only:[:create]

        resources :products, only: [], controller: '/spree/admin/products' do
          get :related, on: :member
          resources :relations, controller: '/spree/api/relations' do
            collection do
              post :update_positions
            end
          end
        end

        resources :orders, only: [] do
          patch :calculate_shipping, on: :member
          put   :remove_promotions, on: :member
        end

        resources :checkouts, only: [:update] do
          member do
            put :reset
          end
        end

        resources :store_credit_events, only: [] do
          collection do
            get :mine
          end
        end

        resources :gift_cards, only: [] do
          collection do
            post :redeem
          end
        end
      end
    end

    namespace :admin do
      resources :users, only: [] do
        resources :gift_cards, only: [] do
          collection do
            get :lookup
            post :redeem
          end
        end

        collection do
          resources :gift_cards, only: [:index]
        end
      end

      resources :orders, only: [] do
        resources :gift_cards, only: [:edit, :update] do
          member do
            put :send_email
            put :deactivate
          end
        end
      end
    end
  end

end

app/views/spree/admin/orders/_cart_gift_card_details.html.erb
<% item.gift_cards.each do |gift_card| %>
    <%= render partial: "gift_card_details", locals: { gift_card: gift_card } %>
<% end %>

app/views/spree/admin/orders/_confirmation_gift_card_details.html.erb
<fieldset class="no-border-bottom">
  <legend align="center" data-hook="gift-card">
    <%= Spree.t(:gift_cards_details) %>
  </legend>
</fieldset>

<table>
  <colgroup>
    <col style="width: 15%;" />
    <col style="width: 15%;" />
    <col style="width: 15%;" />
    <col style="width: 30%;" />
    <col style="width: 10%;" />
    <col style="width: 15%;" />
  </colgroup>

  <thead>
  <th><%= Spree.t(:recipient_email) %></th>
  <th><%= Spree.t(:recipient_name) %></th>
  <th><%= Spree.t(:purchaser_name) %></th>
  <th><%= Spree.t(:gift_message) %></th>
  <th><%= Spree.t(:send_email_at) %></th>
  </thead>


  <tbody>
  <% @order.line_items.flat_map(&:gift_cards).each do |gift_card| %>
      <tr>
        <td>
          <%= gift_card.recipient_email || "n/a" %>
        </td>
        <td>
          <%= gift_card.recipient_name || "n/a" %>
        </td>
        <td>
          <%= gift_card.purchaser_name || "n/a" %>
        </td>
        <td>
          <%= gift_card.gift_message || "n/a" %>
        </td>
        <td>
          <%= gift_card.formatted_send_email_at || "Immediately" %>
        </td>
        <td class="actions">
          <%= link_to '', edit_admin_order_gift_card_path(@order, gift_card), :class => 'fa fa-edit no-text with-tip', :title => Spree.t('actions.edit') %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/orders/_gift_card_details.html.erb
<br><strong><%= Spree.t('admin.gift_cards.redemption_code') %>:</strong> <%= gift_card.redemption_code %>
<br>
<% if gift_card.deactivated? %>
    <b>DEACTIVATED</b>
<% end %>
<% edit_text = gift_card.deactivated? ? "(Details)" : "(Edit Details)" %>
<%= link_to edit_text, spree.edit_admin_order_gift_card_path(@order, gift_card), class: 'edit-gift-card-details' %>

app/views/spree/admin/orders/_gift_card_redemption_codes.html.erb
<% item.line_item.gift_cards.each do |gift_card| %>
    <br><strong><%= Spree.t('admin.gift_cards.redemption_code') %>:</strong> <%= gift_card.redemption_code %>
<% end %>

app/views/spree/admin/orders/_shipment_note.html.erb
<tr class="edit-note is-hidden">
  <td colspan="5">
    <label>Note:</label>
    <%= text_field_tag :note, shipment.note, class: "form-control" %>
  </td>
  <td class="actions">
    <% if can? :update, shipment %>
      <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-note btn btn-primary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
      <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-note btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
    <% end %>
  </td>
</tr>
<tr class="show-note">
	<td colspan="5" class="shipment-note">
		<% if shipment.note.present? %>
		<strong>Note:</strong> <%= shipment.note %>
		<% else %>
		No note added
		<% end %>
	</td>
	<td class="actions text-center">
		<% if can? :update, shipment %>
		<%= link_to_with_icon 'edit', Spree.t('edit'), "#", class: 'edit-note btn btn-primary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
		<% end %>
	</td>
</tr>

app/views/spree/admin/orders/_shipments_gift_card_details.html.erb
<% item.line_item.gift_cards.each do |gift_card| %>
    <%= render partial: "gift_card_details", locals: { gift_card: gift_card } %>
<% end %>